### PR TITLE
Added Senior Moderator to !staff

### PR DESCRIPTION
**Pull request by benrobson**

### CODE REVIEW

**Comment by MrScopes** [comment]
is this really necessary? sr mods aren't really the ones you should be calling for hackers

**Comment by benrobson** [comment]
This was suggested by another Senior Staff member, although they shouldn't be called for hackers, if no one else is on or accessible, they should be notified.

**Comment by jellz** [comment]
It was a planned addition anyway, shadow just beat me to it

**Comment by MrScopes** [comment]
> This was suggested by another Senior Staff member, although they shouldn't be called for hackers, if no one else is on or accessible, they should be notified.

I guess

**Pull request closed without merging**
